Feature: Game of Life with basic rules

Scenario: Cells with two or three neighbours survive

Given a grid which looks like
"""
    ....................
    ..#..........##.....
    .#.#.........##.....
    .#.#................
    ..#.................
    ....................
"""
When we step to the next generation
Then the grid should look like
"""
    ....................
    ..#..........##.....
    .#.#.........##.....
    .#.#................
    ..#.................
    ....................
"""