Feature: Game of Life with basic rules

Scenario: Cells with two or three neighbours survive

Given a grid which looks like
"""
    ....................
    ..#..........##.....
    .#.#.........##.....
    .#.#................
    ..#.................
    ....................
"""
When we step to the next generation
Then the grid should look like
"""
    ....................
    ..#..........##.....
    .#.#.........##.....
    .#.#................
    ..#.................
    ....................
"""

Scenario: Cells with one or no neighbour die

Given a grid which looks like
"""
    .........
    .#...#...
    .....#...
    .........
"""
When we step to the next generation
Then the grid should look like
"""
    .........
    .........
    .........
    .........
"""

Scenario: Cells with more than 3 neighbours die

Given a grid which looks like
"""
    .........
    ....#....
    ...#.#...
    ..#.#.#..
    ...#.#...
    ....#....
    .........
"""
When we step to the next generation
Then the grid should look like
"""
    .........
    ....#....
    ...#.#...
    ..#...#..
    ...#.#...
    ....#....
    .........
"""

Scenario: Cells with three neighbours are born

Given a grid which looks like
"""
    .........
    ....##...
    .....#...
    .........
"""
When we step to the next generation
Then the grid should look like
"""
    .........
    ....##...
    ....##...
    .........
"""
