Feature: We can set up the game of life

Scenario: The grid starts empty

Given the game is running
Then the grid should look like
"""
    ....................
    ....................
    ....................
    ....................
    ....................
"""

Scenario: We can toggle the grid

Given the game is running
When we toggle the cells at
"""
    ....................
    .##.................
    ..#.................
    ....................
    ....................
"""
And we toggle the cells at
"""
    ....................
    ..#.................
    ....................
    ....................
    ....................
"""
Then the grid should look like
"""
    ....................
    .#..................
    ..#.................
    ....................
    ....................
"""